---

  - src: git+git@github.com:zenoamaro/ansible-supervisord.git
    version: master
    name: supervisord

  - src: git+git@github.com:balanced-cookbooks/ansible-rsyslog.git
    name: rsyslog
    version: master

  - src: git+git@github.com:balanced-cookbooks/ansible-postgresql-client.git
    version: master
    name: postgresql-client

  - src: git+git@github.com:balanced-cookbooks/ansible-base.git
    version: b728fd403c6c900dd6bcd872c956839665e561b9
    name: base

  - src: gpstathis.elasticsearch
    name: elasticsearch

  - src: ANXS.postgresql
    name: postgresql

  - src: Stouts.rabbitmq
    name: rabbitmq

  - src: DavidWittman.redis
    name: redis
