---

- hosts: all
  sudo: yes
  vars:
    citadel_bucket: 'balanced-citadel'

  vars_files:
    - 'defaults/main.yml'

  handlers:
    - include: handlers/main.yml

  roles:
    - base

  tasks:
    - name: Fetch deploy key?
      debug: msg="{{ lookup('citadel', '/deploy_key/deploy.pem') }}"
      tags: citadel

    - name: Write the deploy key for cloning
      tags: deploy-key
      sudo: false
      lineinfile:
        dest=~/.ssh/deploy_key
        line="{{ lookup('citadel', '/deploy_key/deploy.pem') }}"
        state=present
        create=yes
        mode='0400'

    # http://hakunin.com/six-ansible-practices
    - name: ensure github.com is a known host
      tags: balanced-install
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    - name: install balanced
      sudo: no
      include: tasks/main.yml
      tags: balanced-install
      vars:
        balanced_install_method: apt
        balanced_apt_version: null
