---

- hosts: all
  sudo: yes
  vars:
    citadel_bucket: 'balanced-citadel'
    rabbitmq_vhosts:
      - localhost
    redis_bind: 127.0.0.1
    postgresql_ext_install_contrib: yes
    postgresql_client_encoding: utf8

  vars_files:
    - roles/elasticsearch/vars/sample.yml
    - defaults/main.yml

  roles:
    - base
    - elasticsearch
    - postgresql
    - rabbitmq
    - redis

  handlers:
    - include: handlers/main.yml

  tasks:
    - name: PostgreSQL | add balanced as a super user
      tags: setup-db
      postgresql_user: >-
        name=balanced
        password=balanced
        encrypted=no
        role_attr_flags=SUPERUSER
        login_host=localhost
        state=present

    - name: PostgreSQL | create the balanced db
      tags: setup-db
      postgresql_db: >-
        name=balanced
        owner=balanced
        encoding=UTF-8
        lc_collate='en_US.UTF-8'
        lc_ctype='en_US.UTF-8'
        template=template0
        login_host=localhost
        login_user=balanced
        login_password=balanced
        state=present

    - name: Fetch deploy key?
      debug: msg="{{ lookup('citadel', '/deploy_key/deploy.pem') }}"
      tags: citadel

    - name: Write the deploy key for cloning
      tags: deploy-key
      sudo: false
      lineinfile:
        dest=~/.ssh/deploy_key
        line="{{ lookup('citadel', '/deploy_key/deploy.pem') }}"
        state=present
        create=yes
        mode='0400'

    # http://hakunin.com/six-ansible-practices
    - name: ensure github.com is a known host
      tags: balanced-install
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    - name: install balanced
      sudo: no
      include: tasks/main.yml
      tags: balanced-install
      vars:
        balanced_install_method: apt
        balanced_apt_version: null

    - name: install pip dirs for vagrant user
      include: roles/base/tasks/py.yml
      tags: balanced-install-development
      vars:
        users:
          - name: vagrant
        pypi_username: omnibus
        pypi_password: "{{ lookup('citadel', '/omnibus/devpi_password').strip() }}"

    - name: install balanced development tools
      include: tasks/development.yml
      tags: balanced-install-development
