---

- name: checkout source
  sudo: no
  git: >
    repo="{{ balanced_git_repo }}"
    dest="~{{ ansible_ssh_user }}/balanced"
    version="{{ balanced_git_version }}"
    key_file=/home/{{ ansible_ssh_user }}/.ssh/deploy_key

# - name: install from source
#   pip: >
#     name="~{{ ansible_ssh_user }}/balanced/setup.py"
#     extra_args='-e .'
