---

- name: install virtualenv
  sudo: yes
  pip: name=virtualenv

- name: create the virtualenv
  sudo: no
  command: >
    virtualenv balanced --no-site-packages
    creates=/home/{{ ansible_ssh_user }}/.virtualenvs/balanced/bin/activate

- name: checkout source
  sudo: no
  git: >
    repo="{{ balanced_git_repo }}"
    dest="~{{ ansible_ssh_user }}/balanced"
    version="{{ balanced_git_version }}"
    key_file=/home/{{ ansible_ssh_user }}/.ssh/deploy_key

- name: install from source
  sudo: no
  pip: >
    name=.
    chdir="/home/{{ ansible_ssh_user }}/balanced"
    virtualenv=/home/{{ ansible_ssh_user }}/.virtualenvs/balanced
    extra_args='-e'
  tags: pip-install
