---

- name: user
  user: >
    name=balanced
    state=present
    shell=/bin/bash
    createhome=no
    home=/opt/balanced

- include: install_git.yml
  tags: [balanced, balanced-install]
  when: balanced_install_method == 'git'

- include: install_apt.yml
  tags: [balanced, balanced-install]
  sudo: yes
  when: balanced_install_method == 'apt'

- include: base.yml
  sudo: yes
  tags: [balanced, balanced-install]
